### PR TITLE
fix: dont resume state when app gets killed

### LINKED ISSUE #824: Not showing reconnect overlay after long time in background
I saw now 2 times that after very long being in background (> 12 hours) the app has 0 connections, the profile icon has the ? placeholder and after a while it start loading the inventory request and recovers. This is good that it recovers by itself, but it is missing the overlay with the reconnect message and restart button usually shown in that case.

### PR DESCRIPTION
**Pull request by wodoro**
- fixes #824 

This will make the app always start from the bootstrap screen no matter how it is killed. if it starts from a dead state, it needs to go through bootstrap instead of jumping straight to the app

you can test the before/after this PR by killing the app and starting it again using this:
```
# Restart ADB daemon as root
adb root

# Now you can use kill commands
adb shell kill -9 $(adb shell pidof network.bisq.mobile.node.debug)
```

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved app initialization and recovery when the system terminates the application process, ensuring proper reinitiation on startup.

### CODE REVIEW

File: apps/nodeApp/src/androidMain/kotlin/network/bisq/mobile/android/node/NodeMainActivity.kt [hunk 1]
```diff
@@ -12,7 +13,13 @@ class NodeMainActivity : MainActivity() {
     override fun onCreate(savedInstanceState: Bundle?) {
         // Install splash screen before super.onCreate to prevent UI blocking
         installSplashScreen()
-        super.onCreate(savedInstanceState)
+
+        if (MainApplication.wasProcessDead.getAndSet(false)) {
```
Comment (rodvar) [inline apps/nodeApp/src/androidMain/kotlin/network/bisq/mobile/android/node/NodeMainActivity.kt]: code dup - could be deletected to MainApplication and call from both activities.
