### PR TITLE
Bugfix/port used tor issue

### LINKED ISSUE #597: Investigate bootstrap happening in all devices on multiple-devices test runs
See stacktrace below, investigate and fix

```
2025-08-28 15:31:19.871 15970-16296 KmpTorService           network.bisq.mobile.node.debug       I  Tor Notice: Socks listener listening on port 41291.
2025-08-28 15:31:19.871 15970-16296 KmpTorService           network.bisq.mobile.node.debug       I  Socks port: 41291
2025-08-28 15:31:19.872 15970-16120 KmpTorService           network.bisq.mobile.node.debug       I  Path to controlPortFile: /data/user/0/network.bisq.mobile.node.debug/files/Bisq2_mobile/tor/control-port.txt
2025-08-28 15:31:19.873 15970-16120 KmpTorService           network.bisq.mobile.node.debug       I  readControlPort iterations=1
2025-08-28 15:31:19.873 15970-16120 KmpTorService           network.bisq.mobile.node.debug       I  We detected modification change of controlPortFile: /data/user/0/network.bisq.mobile.node.debug/files/Bisq2_mobile/tor/control-port.txt
2025-08-28 15:31:19.874 15970-16120 KmpTorService           network.bisq.mobile.node.debug       I  Control port read from control.txt file: 40981
2025-08-28 15:31:19.876 15970-16286 KmpTorService           network.bisq.mobile.node.debug       I  Tor daemon started
2025-08-28 15:31:19.877 15970-16117 KmpTorService           network.bisq.mobile.node.debug       I  Wrote external_tor.config to /data/user/0/network.bisq.mobile.node.debug/files/Bisq2_mobile/tor/external_tor.config
                                                                                                    
                                                                                                    UseExternalTor 1
                                                                                                    CookieAuthentication 1
                                                                                                    CookieAuthFile /data/user/0/network.bisq.mobile.node.debug/files/Bisq2_mobile/tor/control_auth_cookie
                                                                                                    SocksPort 127.0.0.1:41291
                                                                                                    ControlPort 127.0.0.1:40981
2025-08-28 15:31:20.388 15970-16117 KmpTorService           network.bisq.mobile.node.debug       I  Verified control port 40981 is accessible
2025-08-28 15:31:20.389 15970-16117 KmpTorService           network.bisq.mobile.node.debug       I  kmp-tor startup completed
2025-08-28 15:31:20.390 15970-16116 NodeApplic...trapFacade network.bisq.mobile.node.debug       I  Bootstrap: Tor daemon initialized successfully
2025-08-28 15:31:20.391 15970-16116 NodeApplic...trapFacade network.bisq.mobile.node.debug       I  Bootstrap: Tor initialization completed - application state observer already set up
2025-08-28 15:31:20.391 15970-16121 NodeApplic...trapFacade network.bisq.mobile.node.debug       I  Bootstrap: Tor initialization wait completed
2025-08-28 15:31:20.392 15970-16121 NodeSettin...viceFacade network.bisq.mobile.node.debug       I  NodeSettingsServiceFacade activated
2025-08-28 15:31:20.392 15970-16121 NodeMainPresenter       network.bisq.mobile.node.debug       I  Start initializing applicationService
2025-08-28 15:31:20.630 15970-16121 AndroidApp...ionService network.bisq.mobile.node.debug       I  pruneAllBackups took 237 ms
2025-08-28 15:31:21.741   922-922   audit                   auditd                               E  type=1300 audit(1756375281.736:1932): arch=c00000b7 syscall=29 success=no exit=-13 a0=b a1=894b a2=b400007da51e32b4 a3=7fdf04bf50 items=0 ppid=15970 pid=16293 auid=4294967295 uid=10294 gid=10294 euid=10294 suid=10294 fsuid=10294 egid=10294 sgid=10294 fsgid=10294 tty=(none) ses=4294967295 comm="libtorexec.so" exe="/data/app/~~-TQ5SDNDYW_tOKPR5kaf3Q==/network.bisq.mobile.node.debug-I3dSAx6yWAxqeSMrv7aaaA==/lib/arm64/libtorexec.so" subj=u:r:untrusted_app:s0:c38,c257,c512,c768 key=(null)
2025-08-28 15:31:21.917   922-922   audit                   auditd                               E  type=1300 audit(1756375281.912:1933): arch=c00000b7 syscall=29 success=no exit=-13 a0=b a1=894b a2=b400007da51e32b4 a3=7fdf04bf50 items=0 ppid=15970 pid=16293 auid=4294967295 uid=10294 gid=10294 euid=10294 suid=10294 fsuid=10294 egid=10294 sgid=10294 fsgid=10294 tty=(none) ses=4294967295 comm="libtorexec.so" exe="/data/app/~~-TQ5SDNDYW_tOKPR5kaf3Q==/network.bisq.mobile.node.debug-I3dSAx6yWAxqeSMrv7aaaA==/lib/arm64/libtorexec.so" subj=u:r:untrusted_app:s0:c38,c257,c512,c768 key=(null)
2025-08-28 15:31:22.019 15970-16121 AndroidApp...ionService network.bisq.mobile.node.debug       I  readAllPersisted took 1389 ms
2025-08-28 15:31:22.019 15970-16121 AndroidApp...ionService network.bisq.mobile.node.debug       I  Starting securityService.initialize()
2025-08-28 15:31:22.021 15970-16121 AndroidApp...ionService network.bisq.mobile.node.debug       I  securityService.initialize() completed with result: true
2025-08-28 15:31:22.021 15970-16121 NodeApplic...trapFacade network.bisq.mobile.node.debug       I  Bootstrap: Application state changed to: INITIALIZE_NETWORK
2025-08-28 15:31:22.022 15970-16121 NodeApplic...trapFacade network.bisq.mobile.node.debug       I  Bootstrap: Starting timeout for stage: Bootstrap to P2P network (20s)
2025-08-28 15:31:22.022 15970-16117 NodeApplic...trapFacade network.bisq.mobile.node.debug       E  Bootstrap: Timeout job cancelled for stage: Launching Tor daemon...
                                                                                                    kotlinx.coroutines.JobCancellationException: StandaloneCoroutine was cancelled; job=StandaloneCoroutine{Cancelling}@8aebc7a
2025-08-28 15:31:22.024 15970-16121 AndroidApp...ionService network.bisq.mobile.node.debug       I  Starting networkService.initialize()
2025-08-28 15:31:22.028 15970-16121 NodeConnectivityService network.bisq.mobile.node.debug       D  Connectivity is being monitored
2025-08-28 15:31:22.029 15970-16121 NodeMainPresenter       network.bisq.mobile.node.debug       D  Application service created, monitoring connectivity..
2025-08-28 15:31:22.092 15970-16320 AndroidApp...ionService network.bisq.mobile.node.debug       E  networkService.initialize() failed
                                                                                                    java.util.concurrent.CompletionException: java.lang.NullPointerException: Attempt to invoke virtual method 'int bisq.common.network.Address.getPort()' on a null object reference
                                                                                                    	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:291)
                                                                                                    	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:296)
                                                                                                    	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1746)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1156)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:651)
                                                                                                    	at java.lang.Thread.run(Thread.java:1119)
                                                                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int bisq.common.network.Address.getPort()' on a null object reference
                                                                                                    	at bisq.network.p2p.node.transport.TorTransportService.getServerSocket(TorTransportService.java:68)
                                                                                                    	at bisq.network.p2p.node.Node.createServerAndListen(Node.java:245)
                                                                                                    	at bisq.network.p2p.node.Node.initialize(Node.java:220)
                                                                                                    	at bisq.network.p2p.ServiceNode.getInitializedDefaultNode(ServiceNode.java:271)
                                                                                                    	at bisq.network.p2p.ServiceNodesByTransport.lambda$getInitializedDefaultNodeByTransport$1(ServiceNodesByTransport.java:142)
                                                                                                    	at bisq.network.p2p.ServiceNodesByTransport.$r8$lambda$y4pBO1vy7bTFNomdmryLcUGipuM(Unknown Source:0)
                                                                                                    	at bisq.network.p2p.ServiceNodesByTransport$$ExternalSyntheticLambda13.get(D8$$SyntheticClass:0)
                                                                                                    	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1744)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1156) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:651) 
                                                                                                    	at java.lang.Thread.run(Thread.java:1119) 
2025-08-28 15:31:22.093 15970-16320 AndroidApp...ionService network.bisq.mobile.node.debug       E  Initializing applicationService failed
                                                                                                    java.util.concurrent.CompletionException: java.lang.NullPointerException: Attempt to invoke virtual method 'int bisq.common.network.Address.getPort()' on a null object reference
                                                                                                    	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:291)
                                                                                                    	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:296)
                                                                                                    	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1746)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1156)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:651)
                                                                                                    	at java.lang.Thread.run(Thread.java:1119)
                                                                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int bisq.common.network.Address.getPort()' on a null object reference
                                                                                                    	at bisq.network.p2p.node.transport.TorTransportService.getServerSocket(TorTransportService.java:68)
                                                                                                    	at bisq.network.p2p.node.Node.createServerAndListen(Node.java:245)
                                                                                                    	at bisq.network.p2p.node.Node.initialize(Node.java:220)
                                                                                                    	at bisq.network.p2p.ServiceNode.getInitializedDefaultNode(ServiceNode.java:271)
                                                                                                    	at bisq.network.p2p.ServiceNodesByTransport.lambda$getInitializedDefaultNodeByTransport$1(ServiceNodesByTransport.java:142)
                                                                                                    	at bisq.network.p2p.ServiceNodesByTransport.$r8$lambda$y4pBO1vy7bTFNomdmryLcUGipuM(Unknown Source:0)
                                                                                                    	at bisq.network.p2p.ServiceNodesByTransport$$ExternalSyntheticLambda13.get(D8$$SyntheticClass:0)
                                                                                                    	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1744)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1156) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:651) 
                                                                                                    	at java.lang.Thread.run(Thread.java:1119) 
2025-08-28 15:31:22.093 15970-16320 NodeApplic...trapFacade network.bisq.mobile.node.debug       I  Bootstrap: Application state changed to: FAILED
2025-08-28 15:31:22.095 15970-16115 NodeApplic...trapFacade network.bisq.mobile.node.debug       E  Bootstrap: Timeout job cancelled for stage: Bootstrap to P2P network
            
```

### PR DESCRIPTION
**Pull request by rodvar**
- fixes #597 
 - error handling on stopping tor before bootstrap
 - external tor file verification added as part of the suspend fun to make sure to progress after the file is ready with the connection data to be used
 - 2nd batch of node performance upgrades (addresses skipped frames warnings on bootstrap)
 - enforce single-activity arch with manifest declaration
 - temporarily add jetifier (probably can be remove when we bump up libs in incoming PR)

## Summary by CodeRabbit

- New Features
  - Added richer bootstrap error messages and a “Ready to retry” state.
  - Added detailed localized strings for Afrikaans, Czech, German, Italian, Pidgin, Portuguese (BR), Russian.

- Bug Fixes
  - Prevents duplicate app instances on relaunch.
  - More reliable Tor setup with external-config validation, clearer failure reporting, improved timeout/retry and bootstrap error flows.
  - Smoother startup and rendering via refined splash handling and hardware acceleration.

- Chores
  - Build/tooling compatibility update: AndroidX Jetifier enabled; debug builds disable code/resource shrinking.

### CODE REVIEW

File: androidNode/src/androidMain/kotlin/network/bisq/mobile/android/node/MainApplication.kt [hunk 1]
```diff
@@ -52,7 +55,15 @@ class MainApplication : BisqMainApplication(), ComponentCallbacks2 {
...
 
     override fun onCreated() {
-        setupBisqCoreStatics()
+        // Use runBlocking for essential system initialization that must complete before app continues
+        // This is acceptable here because:
+        // 1. It's Application.onCreate() - the right place for critical setup
+        // 2. setupBisqCoreStatics() configures essential system components (BouncyCastle, Facades)
+        // 3. The app cannot function without these being initialized
+        // 4. It's a one-time operation during app startup
+        runBlocking(Dispatchers.IO) {
```
Comment (salottodev) [inline androidNode/src/androidMain/kotlin/network/bisq/mobile/android/node/MainApplication.kt:64]: @rodvar This blocks the Main Thread and can lead to ANRs. We should avoid runBlocking here and instead move this initialization to a background coroutine.

Comment (rodvar) [reply androidNode/src/androidMain/kotlin/network/bisq/mobile/android/node/MainApplication.kt:64]: Thanks for taking time to review this @salottodev 

I hope my comments on why I used runBlocking here were clearer, I agree with you technically speaking and in most cases but for this particular case it's actually better because:

 - in Android activity onCreate it won't try to render UI until it finish running
 - The app cannot function without these components (critical init)
 - It’s one-time, deterministic setup 
 
 And also its just a few ms to run, if we ever need to grow this into I/O operations I would definitely change it but I don't foresee that case anytime soon.
 Let me know if this makes sense to you - should I change the wording in the comments? happy to discuss further

Comment (salottodev) [reply androidNode/src/androidMain/kotlin/network/bisq/mobile/android/node/MainApplication.kt:64]: Can we move this data loading to the splash screen? If not, I think we should try to find the way of avoiding this. It is never a good practice to block the main thread.

**Comment by wodoro** [comment]
hey @rodvar
I was reviewing part of this tonight
why was `setupBisqCoreStatics` changed to be a suspend ?
I don't see any suspend function being used inside, and it's not doing much, and we are blocking on it anyway, so what was the reason exactly? (a comment in the code would be necessary in such cases)
