### PR TITLE
fix: make sure backup&restore continues in service scope

### LINKED ISSUE #985: Refactor RestoreBackup to use presenter scope for configuration change survival
## Problem

The RestoreBackup composable currently uses `rememberCoroutineScope()` for executing backup restoration operations. This means that configuration changes like screen rotation will cancel the restoration mid-flight, potentially corrupting data or leaving the app in an inconsistent state.

## Context

A TODO comment was added in the code identifying this architectural issue:
```kotlin
// TODO: needs refactor: Important tasks must be executed on presenter scope, a simple screen rotation will cancel the composable scope
```

Location: `shared/presentation/src/androidMain/kotlin/network/bisq/mobile/presentation/ui/components/RestoreBackup.kt`

## Required Changes

The restoration logic (file reading, decryption, validation) should be moved to the presenter layer where it can use a lifecycle-aware scope that survives configuration changes. This aligns with the architectural pattern that critical operations requiring completion regardless of UI lifecycle events should execute in presenter scope.

## References

- PR #984: Refactor dispatcher usages
- Comment: https://github.com/bisq-network/bisq-mobile/pull/984#discussion_r2571291583
- Requested by: @wodoro

### PR DESCRIPTION
**Pull request by wodoro**
resolves #985

some changes were essential for correctness (like the move of `view` to main presenter)

I refactored the resources screen while at it

this should also fix the issue with restore file size limit, as it directly uses the stream now instead of reading into memory

## Summary by CodeRabbit

* **New Features**
  * Added backup and restore functionality allowing users to securely backup and restore application data.
  * Added "Backup & Restore" menu option in settings for easy access.
  * Support for password-protected backups to enhance security.
  * File restoration with validation and error handling for corrupted or invalid backups.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

**Comment by rodvar** [comment]
rebased and fixed conflicts

File: apps/nodeApp/src/androidMain/kotlin/network/bisq/mobile/node/settings/backup/presentation/BackupUiState.kt [hunk 1]
```diff
@@ -0,0 +1,10 @@
+package network.bisq.mobile.node.settings.backup.presentation
+
+import android.net.Uri
+
+data class BackupUiState(
```
Comment (rodvar) [inline apps/nodeApp/src/androidMain/kotlin/network/bisq/mobile/node/settings/backup/presentation/BackupUiState.kt]: nice already incorporating this MVI(P) style in 👍

**Review by rodvar — APPROVED** [review]
ACK

thank you
