### PR TITLE
fix: make ui rounded corners more consistent

### LINKED ISSUE #930: Make component designs more consistent
This is a small list to fix, feel free to add to it if you found anything else.

1. Select component has different height and rounded corners shape from normal text input:

Image

-------------------

2. Rounded corners are not exactly the same across the app.
Note: logs in chat with different corner radius can be intentional and a good thing. the focus is on the chat bubble.

Image

Image

Image

Image

-------------------

3. Inputs change shape when in focus:

Image

Image

### PR DESCRIPTION
**Pull request by wodoro**
resolves #930

- Created a new constant for border radius
- Fixed white background bleed in ToggleTab
- Used text field directly in bisq select trigger for visual consistency

6-b
6-a
5-b
5-a
4-b
4-a
3-b
3-a
2-b
2-a
1-b
1-a

## Summary by CodeRabbit

* **New Features**
  * Read-only text field support for form inputs.
  * Added an outlined chat icon variant.

* **Style**
  * Standardized rounded corner sizes across cards, dialogs, sheets, chips, buttons and snackbars for a consistent look.
  * Select control now uses a text-field trigger with improved focus/blur behavior.
  * Refined chat row visuals and spacing; updated chat icon styling.

### CODE REVIEW

File: shared/presentation/src/commonMain/kotlin/network/bisq/mobile/presentation/ui/components/atoms/BisqCard.kt [hunk 1]
```diff
@@ -20,15 +20,14 @@ import network.bisq.mobile.presentation.ui.theme.BisqUIConstants
...
-    borderRadius: Dp = BisqUIConstants.ScreenPaddingHalf,
     horizontalAlignment: Alignment.Horizontal = Alignment.Start,
     verticalArrangement: Arrangement.Vertical = Arrangement.Top,
     backgroundColor: Color = BisqTheme.colors.dark_grey40,
     content: @Composable ColumnScope.() -> Unit
 ) {
     Column(
         modifier = modifier
-            .clip(RoundedCornerShape(borderRadius))
+            .clip(RoundedCornerShape(BisqUIConstants.BorderRadius))
```
Comment (rodvar) [inline shared/presentation/src/commonMain/kotlin/network/bisq/mobile/presentation/ui/components/atoms/BisqCard.kt]: 👏
