### PR TITLE
fix: make BasePresenter use JobManager scope & fix iOS coroutine handler

### LINKED ISSUE #1033: Refactor coroutines disposal
consider refactoring the coroutines disposal

```
Remove scope recreation from dispose() since the scopes won't be reused anymore
Make disposal final - once disposed, the manager shouldn't be usable
Clean up the iOS-specific logic - the early return might not be needed if we're not recreating scopes
Here's how the simplified dispose() could look:

override suspend fun dispose() {
    runCatching {
        jobsMutex.withLock {
            jobs.forEach {
                runCatching { it.cancel() }.onFailure {
                    log.w { "Failed to cancel job: ${it.message}" }
                }
            }
            jobs.clear()
        }

        runCatching { uiScope.cancel() }.onFailure {
            log.w { "Failed to cancel UI scope: ${it.message}" }
        }
        runCatching { ioScope.cancel() }.onFailure {
            log.w { "Failed to cancel IO scope: ${it.message}" }
        }
    }.onFailure {
        log.e(it) { "Failed to dispose coroutine jobs" }
    }
}
```

### PR DESCRIPTION
**Pull request by wodoro**
resolves #1033

## Summary by CodeRabbit

* **Refactor**
  * Centralized coroutine exception handling and unified coroutine scope usage across presenters and runtime, exposing a handler property for global routing.
* **Chores**
  * iOS build resource phase updated for cleaner build scripting.
* **Tests**
  * Tests updated to initialize DI with the shared exception handler and job manager to better reflect runtime behavior.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

**Comment by rodvar** [comment]
rebased to main

File: shared/domain/src/commonMain/kotlin/network/bisq/mobile/domain/utils/CoroutineJobsManager.kt [hunk 1]
```diff
@@ -71,27 +71,11 @@ class DefaultCoroutineJobsManager :
     override fun getScope(): CoroutineScope = scope
 
     override suspend fun dispose() {
-        if (isIOS) {
-            // On iOS, don't dispose scopes during shutdown to avoid crashes
-            // The system will clean up when the app terminates
-            return
```
Comment (rodvar) [inline shared/domain/src/commonMain/kotlin/network/bisq/mobile/domain/utils/CoroutineJobsManager.kt]: I've quickly tested and this is not necessary if we decide to get rid of the recreation of scopes 👍

**Comment by wodoro** [comment]
build error due to this:

```
bisq-mobile/apps/nodeApp/src/androidMain/kotlin/network/bisq/mobile/node/common/domain/service/accounts/NodeFiatAccountsServiceFacade.kt:60:28 Unresolved reference 'updatePaymentAccount'.
```

**Comment by rodvar** [comment]
> build error during test in prepush due to this:
> 
> ```
> bisq-mobile/apps/nodeApp/src/androidMain/kotlin/network/bisq/mobile/node/common/domain/service/accounts/NodeFiatAccountsServiceFacade.kt:60:28 Unresolved reference 'updatePaymentAccount'.
> ```
> 
> edit: probably my local maven is having problem

wod several tests are failing in CI, I'll download the branch and test a bit now and do a first pass for 👍

**Review by rodvar — APPROVED** [review]
I've done a first pass and I think this implementation is much better than what we had:

 - cleaner API
 - remove platform specific hacks we needed before until we learn we could inject the coroutine exception handler in ios too
 - better scope management
 - simpler code

I review the failing tests and they just need adaptation. I might collab proposing fixes for you to review so we can merge this soon :)

**Review by rodvar — CHANGES_REQUESTED** [review]
@wodoro please review my pre-merge commit fixing the tests.

Also, before merging this one. I'm testing the apps and for node it looks like the tor startup is slower with this setup and 60 secs timeout isn't enough anymore? it's consistently timeouting at ~45% init.. could you please check on your end?

let's tests all 3 apps together before merging this one 🙏

**Review by rodvar — APPROVED** [review]
ACK
